package programacion.dam.tarea11.ventanas.avion;

import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import programacion.dam.tarea11.util.Util;

/**
 *
 * @author Roach
 */
public class VentanaAvionPrincipal extends javax.swing.JPanel {

    // Atributos
    VentanaAvionLista ventanaAvionLista;
    VentanaAvionCrear ventanaAvionCrear;
    VentanaAvionMix ventanaAvionMix;
    

    /**
     * Creates new form VentanaAvionPrincipal
     */
    public VentanaAvionPrincipal() {
        initComponents();
        ventanaAvionLista = new VentanaAvionLista();
        ventanaAvionCrear = new VentanaAvionCrear();
        ventanaAvionMix = new VentanaAvionMix();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPBotonesAvion = new javax.swing.JPanel();
        bListaAvion = new javax.swing.JButton();
        bBuscarAvion = new javax.swing.JButton();
        bCrearAvion = new javax.swing.JButton();
        bBorrarAvion = new javax.swing.JButton();
        jtbAccionesAvion = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();

        bListaAvion.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        bListaAvion.setText("LISTA");
        bListaAvion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bListaAvionActionPerformed(evt);
            }
        });

        bBuscarAvion.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        bBuscarAvion.setText("BUSCAR");
        bBuscarAvion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarAvionActionPerformed(evt);
            }
        });

        bCrearAvion.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        bCrearAvion.setText("CREAR");
        bCrearAvion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCrearAvionActionPerformed(evt);
            }
        });

        bBorrarAvion.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        bBorrarAvion.setText("BORRAR");
        bBorrarAvion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBorrarAvionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPBotonesAvionLayout = new javax.swing.GroupLayout(jPBotonesAvion);
        jPBotonesAvion.setLayout(jPBotonesAvionLayout);
        jPBotonesAvionLayout.setHorizontalGroup(
            jPBotonesAvionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPBotonesAvionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPBotonesAvionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bBorrarAvion, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                    .addComponent(bListaAvion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bBuscarAvion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bCrearAvion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPBotonesAvionLayout.setVerticalGroup(
            jPBotonesAvionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBotonesAvionLayout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addComponent(bListaAvion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(bBuscarAvion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(bCrearAvion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(bBorrarAvion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        jtbAccionesAvion.setRollover(true);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("AVION");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(jLabel1)
                        .addGap(234, 234, 234))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jtbAccionesAvion, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
                        .addGap(10, 10, 10)))
                .addComponent(jPBotonesAvion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPBotonesAvion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtbAccionesAvion, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public JPanel AvionPrincipalPanel() {
        return this;
    }
    /**
     * Acción abrir nueva ventana Crear avion
     * @param evt 
     */
    private void bCrearAvionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCrearAvionActionPerformed
        // limpiamos el panel
        jtbAccionesAvion.removeAll();
        jtbAccionesAvion.add(ventanaAvionCrear.ventanaNuevoAvion());
        // Cambiamos el aspecto del panel auxiliar y pintamos la vista de Ingresar en cuenta.
        SwingUtilities.updateComponentTreeUI(this); 
    }//GEN-LAST:event_bCrearAvionActionPerformed

    /**
     * Acción abrir nueva ventana buscar avion
     * @param evt 
     */
    private void bBuscarAvionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarAvionActionPerformed
        // limpiamos el panel
        jtbAccionesAvion.removeAll();
        jtbAccionesAvion.add(ventanaAvionMix.ventanaMix(Util.DISTINTIVO_CONSULTAR));
        // Cambiamos el aspecto del panel auxiliar y pintamos la vista de Ingresar en cuenta.
        SwingUtilities.updateComponentTreeUI(this); 
    }//GEN-LAST:event_bBuscarAvionActionPerformed

    /**
     * Acción abrir nueva ventana lista aviones
     * @param evt 
     */
    private void bListaAvionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bListaAvionActionPerformed
        // limpiamos el panel
        jtbAccionesAvion.removeAll();
        jtbAccionesAvion.add(ventanaAvionLista.ventanaListaAvion());
        // Cambiamos el aspecto del panel auxiliar y pintamos la vista de Ingresar en cuenta.
        SwingUtilities.updateComponentTreeUI(this); 
    }//GEN-LAST:event_bListaAvionActionPerformed

    /**
     * Acción abrir nueva ventana borrar avión
     * @param evt 
     */
    private void bBorrarAvionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBorrarAvionActionPerformed
        // limpiamos el panel
        jtbAccionesAvion.removeAll();
        jtbAccionesAvion.add(ventanaAvionMix.ventanaMix(Util.DISTINTIVO_BORRAR));
        // Cambiamos el aspecto del panel auxiliar y pintamos la vista de Ingresar en cuenta.
        SwingUtilities.updateComponentTreeUI(this); 
    }//GEN-LAST:event_bBorrarAvionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBorrarAvion;
    private javax.swing.JButton bBuscarAvion;
    private javax.swing.JButton bCrearAvion;
    private javax.swing.JButton bListaAvion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPBotonesAvion;
    private javax.swing.JToolBar jtbAccionesAvion;
    // End of variables declaration//GEN-END:variables
}
