package programacion.dam.tarea11.ventanas.avion;

import java.util.List;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import programacion.dam.tarea11.beans.Avion;
import programacion.dam.tarea11.dao.AvionDAO;

/**
 *
 * @author Roach
 */
public class VentanaAvionLista extends javax.swing.JPanel {

    // Atributos
    public DefaultTableModel modelo;
    private boolean existenDatos = false;
    
    /**
     * Creates new form VentanaAvionLista
     */
    public VentanaAvionLista() {
        initComponents();
    }
    
    /**
     * Método que pinta el panel en la ventana avion.
     * @return 
     */
    public JPanel ventanaListaAvion() {
        // Pintamos los atributos mas importantes de los articulos.
        String[] columnas = {"Código de Avion", "Modelo", "Numero de Plazas"};
        modelo = new DefaultTableModel(null, columnas);

        tablaListaAvion.setModel(modelo);
        // Cargamos la lista de los aviones.
        this.cargarListaAviones();
        
        existenDatos = true;
        return this;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaListaAvion = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        tablaListaAvion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tablaListaAvion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Codigo", "Modelo", "Numero Plazas"
            }
        ));
        jScrollPane1.setViewportView(tablaListaAvion);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setText("LISTA AVIONES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(178, 178, 178))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
    }// </editor-fold>//GEN-END:initComponents

// ***************************************************************************************************
// ************************************ Utilidades de la Clase ***************************************
// ***************************************************************************************************
    
    /**
     * Método auxiliar que limpia la tabla.
     */
    private void borrarTabla(){
        int longitud = tablaListaAvion.getRowCount()-1;  
        for(int i = longitud; i >= 0; i--){
            modelo.removeRow(i);
        }
    }
    
    /**
     * Método que carga los articulos que se encuentran en la lista temporal,
     * y recoge los datos mas importantes para cargarlos en la tabla.
     */
    private void cargarListaAviones(){
        // Liampiamos la tabla al cargar nuevos aviones, para evitar duplicidades.
        if(existenDatos){
            borrarTabla();
        }
        
        List<Avion> listaAviones = AvionDAO.recuperarAviones();
        
        for(Avion avion : listaAviones){
            // Creamos un array para recoger los datos necesarios de cada avion.
            String numeroPlazas = String.valueOf(avion.getNumeroPlazas());
            String [] fila = {avion.getCodigo(), avion.getModelo(), numeroPlazas};
    
            // Añadimos a la tabla los datos de la cuenta actual.
            modelo.addRow(fila);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaListaAvion;
    // End of variables declaration//GEN-END:variables
}
